###

GET http://localhost/api/tickets/18 HTTP/1.1

###

GET http://localhost/api/blocks/ HTTP/1.1

###

POST http://localhost/api/tickets/ HTTP/1.1
Content-Type: application/json

{
    "state": 1,
    "title": "prova",
    "author_id": 10,
    "category": "inquiry",
    "content": "this is a test!\nquesta è una prova!"
}

###

PUT http://localhost/api/tickets/close/15 HTTP/1.1

###

PUT http://localhost/api/tickets/15 HTTP/1.1
Content-Type: application/json

{
    "category": "inquiry"
}

###

DELETE http://localhost/api/tickets/ HTTP/1.1

###

POST http://localhost/api/blocks/ HTTP/1.1
Content-Type: application/json

{
    "ticket_id": 8,
    "author_id": 1,
    "content": "this is a test!\nquesta è una prova!"
}

###

DELETE http://localhost/api/blocks/9 HTTP/1.1

###

POST http://localhost/api/sessions/ HTTP/1.1
Content-Type: application/json

{
    "username": "enrico_masala",
    "password": "passwd"
}

###

GET http://localhost/api/sessions/current HTTP/1.1

###

DELETE http://localhost/api/sessions/current HTTP/1.1

###

GET http://localhost/api/users/1 HTTP/1.1